# ???????? ????????? ??????????
spring.application.name=autoauction

# ??????????? ? ???????????? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/auto_auction
spring.datasource.username=auto_auction_user
spring.datasource.password=auto_auction_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ?????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson ?????????
spring.jackson.serialization?.indent_output=true

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.packages-to-scan=com.example.autoauction